/**
 * schemas.ts — Bella V3 Contracts-First Schema Definitions
 * Single source of truth for all data shapes shared across workers.
 * RULE: Never rename or remove fields. Only add new fields (additive).
 *       If breaking change needed, bump `v` and add a compatibility shim.
 */

// ─────────────────────────────────────────────
// 1. HeroExtract — generated by HTMLRewriter Fast Track
// ─────────────────────────────────────────────
export interface HeroExtract {
    v: 1;
    url: string;
    h1: string;
    h2: string;
    h3?: string;
    title: string;
    meta_description: string;
    og_title: string;
    og_description: string;
}

export const defaultHeroExtract = (url: string): HeroExtract => ({
    v: 1,
    url,
    h1: "",
    h2: "",
    h3: "",
    title: "",
    meta_description: "",
    og_title: "",
    og_description: "",
});

// ─────────────────────────────────────────────
// 2. FastContext — the buffer-ready payload for Bella's first 20s
// ─────────────────────────────────────────────
export interface FastContext {
    v: 1;
    lid: string;
    ts: string;
    business: {
        name: string;
        domain: string;
        location: string;
        rating: number;
        review_count: number;
        logo_url: string;
    };
    hero: HeroExtract;
    person: {
        first_name: string;
        job_title: string;
        tenure: string;
        source: string;
    };
    ads: {
        is_running_ads: boolean;
        estimated_monthly_spend_aud: number;
    };
    numbers: {
        one_real_number_for_opener: number;
    };
}

export const defaultFastContext = (lid: string, url: string): FastContext => ({
    v: 1,
    lid,
    ts: new Date().toISOString(),
    business: {
        name: "",
        domain: url,
        location: "",
        rating: 0,
        review_count: 0,
        logo_url: "",
    },
    hero: defaultHeroExtract(url),
    person: {
        first_name: "",
        job_title: "Unknown Role",
        tenure: "",
        source: "fallback",
    },
    ads: {
        is_running_ads: false,
        estimated_monthly_spend_aud: 0,
    },
    numbers: {
        one_real_number_for_opener: 0,
    },
});

// ─────────────────────────────────────────────
// 3. NormalizedIntel — the single master write to lead:{lid}:intel
//    Derived from SC logic integrated into scraper (E4)
// ─────────────────────────────────────────────
export interface TopFix {
    title: string;
    impact: "high" | "medium" | "low";
    evidence: string[];
    next_step: string;
}

export interface NormalizedIntel {
    v: 1;
    lid: string;
    grade: "A" | "B" | "C" | "D" | "F";
    agent_ranking: string[];
    top_fixes: TopFix[];
    bella_opener: string;
    memory_prefill: {
        crm_detected: boolean;
        runs_ads: boolean;
        country: string;
        currency: string;
    };
    computed_numbers: {
        estimated_weekly_bleed_aud: number;
        confidence: "high" | "medium" | "low";
    };
    deep?: any;
    fast_context: FastContext;
}

export const defaultNormalizedIntel = (lid: string, url: string): NormalizedIntel => ({
    v: 1,
    lid,
    grade: "C",
    agent_ranking: ["chris", "alex", "maddie", "sarah", "james"],
    top_fixes: [],
    bella_opener: "",
    memory_prefill: {
        crm_detected: false,
        runs_ads: false,
        country: "AU",
        currency: "AUD",
    },
    computed_numbers: {
        estimated_weekly_bleed_aud: 0,
        confidence: "low",
    },
    fast_context: defaultFastContext(lid, url),
});

// ─────────────────────────────────────────────
// 4. ConversationPlan — Tools Worker returns next-stage only
// ─────────────────────────────────────────────
export interface ConversationPlan {
    v: 1;
    lid: string;
    stage: string;
    script: string;
    required_vars: string[];
    known_vars: string[];
    guardrails: string[];
}

export const defaultConversationPlan = (lid: string): ConversationPlan => ({
    v: 1,
    lid,
    stage: "stage1_intro",
    script: "",
    required_vars: [],
    known_vars: [],
    guardrails: ["Must call get_conversation_memory before asking any required_vars."],
});

// ─────────────────────────────────────────────
// 5. InjectContextMessage — sent from frontend or scraper into Deepgram WS
// ─────────────────────────────────────────────
export interface InjectContextMessage {
    type: "inject_context";
    v: 1;
    lid: string;
    fast_context: FastContext;
    intel: NormalizedIntel;
}

// ─────────────────────────────────────────────
// 6. MemoryRecord — canonical "known answers" store (prevents blind interrogation)
// ─────────────────────────────────────────────
export interface MemoryEvent {
    t: string;
    event: string;
    value?: unknown;
}

export interface MemoryRecord {
    v: 1;
    lid: string;
    known: Record<string, unknown>;
    asked: Record<string, boolean>;
    history: MemoryEvent[];
}

export const defaultMemoryRecord = (lid: string): MemoryRecord => ({
    v: 1,
    lid,
    known: {
        acv: null,
        runs_ads: false,
        crm: null,
    },
    asked: {
        asked_crm: false,
        asked_acv: false,
    },
    history: [],
});

// ─────────────────────────────────────────────
// HELPER FUNCTIONS
// ─────────────────────────────────────────────

/**
 * sanitizedInt — safely converts messy string numbers to integers.
 * Examples:
 *   sanitizedInt("1.2k")   → 1200
 *   sanitizedInt("$4,500") → 4500
 *   sanitizedInt("38%")    → 38
 *   sanitizedInt(undefined) → 0
 */
export function sanitizedInt(value: unknown): number {
    if (typeof value === "number") return Math.round(value);
    if (!value) return 0;
    const str = String(value).toLowerCase().trim();
    // Handle "k" suffix (e.g., "1.2k" → 1200)
    if (str.endsWith("k")) {
        const num = parseFloat(str.replace("k", ""));
        return isNaN(num) ? 0 : Math.round(num * 1000);
    }
    // Strip all non-numeric except decimal
    const cleaned = str.replace(/[^0-9.]/g, "");
    const num = parseFloat(cleaned);
    return isNaN(num) ? 0 : Math.round(num);
}

/**
 * defaultSafe — merges a partial object onto a full default schema.
 * Ensures no undefined fields ever reach Bella's prompt or KV.
 * Usage: defaultSafe(partialData, defaultFastContext(lid, url))
 */
export function defaultSafe<T extends object>(partial: Partial<T>, defaults: T): T {
    const result = { ...defaults };
    for (const key of Object.keys(partial) as Array<keyof T>) {
        const val = partial[key];
        if (val === undefined || val === null) continue;
        if (
            typeof val === "object" &&
            !Array.isArray(val) &&
            typeof defaults[key] === "object" &&
            defaults[key] !== null
        ) {
            result[key] = defaultSafe(val as Partial<T[keyof T] & object>, defaults[key] as T[keyof T] & object) as T[keyof T];
        } else {
            result[key] = val as T[keyof T];
        }
    }
    return result;
}

/**
 * KV Key Conventions — single source of truth for all KV key names.
 * Import and use these everywhere. Never hardcode key strings.
 */
export const KV_KEYS = {
    intel: (lid: string) => `lead:${lid}:intel`,
    deepIntel: (lid: string) => `lead:${lid}:deepIntel`,
    status: (lid: string) => `lead:${lid}:status`,
    memory: (lid: string) => `lead:${lid}:memory`,
    scriptStages: (lid: string) => `lead:${lid}:script_stages`,
    events: (lid: string) => `lead:${lid}:events`,
} as const;

/** KV TTL: 30 days in seconds */
export const KV_TTL_SECONDS = 2592000;
