name = "cf-hybrid-bella"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[env.production]
name = "cf-hybrid-bella-prod"

[env.staging]
name = "cf-hybrid-bella-staging"

[[d1_databases]]
binding = "BRAIN_D1"
database_name = "brain-hybrid-v1"
database_id = "placeholder"

[[kv_namespaces]]
binding = "LEADS_KV"
id = "0fec6982d8644118aba1830afd4a58cb"

[build]
command = "npm run build"
cwd = "./"
