plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/trentbelasco/Desktop/BELLA_v9_SANDBOX_COMPLETE_SYSTEM/netlify-funnel-sandbox"
publishOrigin = "default"
base = "/Users/trentbelasco/Desktop/BELLA_v9_SANDBOX_COMPLETE_SYSTEM/netlify-funnel-sandbox"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/"
to = "/capture.html"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]